/**
 * Project Document Export
 *
 * Export project documents as ZIP or JSON format.
 */

import JSZip from "jszip";
import { loadProjectDocs, loadProjectMeta } from "./project-store.js";
import type { ProjectDoc } from "./types.js";

// ─── Types ───

export interface DocExportOptions {
  /** Project ID */
  projectId: string;
  /** Document IDs to export (optional, exports all if not provided) */
  docIds?: string[];
  /** Export format (default: "zip") */
  format?: "zip" | "json";
}

export interface DocExportResult {
  /** Generated filename */
  filename: string;
  /** MIME type */
  contentType: string;
  /** Base64-encoded data */
  data: string;
  /** Number of exported documents */
  docCount: number;
  /** IDs of exported documents */
  docIds: string[];
}

// ─── Constants ───

const MAX_ZIP_SIZE_BYTES = 100 * 1024 * 1024; // 100MB
const MAX_DOC_SIZE_BYTES = 50 * 1024 * 1024; // 50MB per doc
const ILLEGAL_FILENAME_CHARS = /[/:*?"<>|\\]/g;

// ─── Filename sanitization ───

/**
 * Sanitize filename for safe filesystem usage
 */
function sanitizeFilename(name: string): string {
  if (!name || name.trim() === "") {
    return "untitled";
  }
  // Replace illegal characters and spaces with dash
  let sanitized = name.replace(ILLEGAL_FILENAME_CHARS, "-").replace(/\s+/g, "-");
  // Trim and collapse multiple dashes
  sanitized = sanitized.trim().replace(/-+/g, "-");
  // Remove leading/trailing dashes
  sanitized = sanitized.replace(/^-+|-+$/g, "");
  // Fallback if empty after sanitization
  if (!sanitized) {
    return "untitled";
  }
  return sanitized;
}

/**
 * Handle filename conflicts by adding numeric suffix
 */
function resolveFilenameConflicts(docs: ProjectDoc[]): Map<string, string> {
  const result = new Map<string, string>();
  const counts = new Map<string, number>();

  for (const doc of docs) {
    const sanitized = sanitizeFilename(doc.name);
    const count = counts.get(sanitized) ?? 0;
    counts.set(sanitized, count + 1);

    if (count === 0) {
      result.set(doc.id, `${sanitized}.md`);
    } else {
      result.set(doc.id, `${sanitized}-${count}.md`);
    }
  }

  return result;
}

// ─── Export functions ───

/**
 * Generate README content for the exported ZIP
 */
function generateReadmeContent(projectName: string, docCount: number): string {
  const date = new Date().toISOString().split("T")[0];
  return `# ${projectName} - Document Export

Exported from OpenClaw on ${date}

This archive contains ${docCount} document(s):

- README.md: This file
- docs.json: Full document data backup (JSON format)
- markdown/*.md: Individual document files

## Usage

You can import these documents back into OpenClaw or use them in any Markdown-compatible tool.

Generated by OpenClaw (https://openclaw.ai)
`;
}

/**
 * Export project documents as ZIP
 */
export async function exportProjectDocs(options: DocExportOptions): Promise<DocExportResult> {
  const { projectId, docIds, format = "zip" } = options;

  // Load project metadata
  const meta = loadProjectMeta(projectId);
  if (!meta) {
    throw new Error(`Project ${projectId} not found`);
  }

  // Load documents
  const allDocs = loadProjectDocs(projectId);
  if (allDocs.length === 0) {
    throw new Error(`Project ${projectId} has no documents`);
  }

  // Filter by docIds if provided
  let docs: ProjectDoc[];
  if (docIds && docIds.length > 0) {
    docs = allDocs.filter((doc) => docIds.includes(doc.id));
    if (docs.length === 0) {
      throw new Error(`No matching documents found for provided docIds`);
    }
  } else {
    docs = allDocs;
  }

  // Check document sizes
  for (const doc of docs) {
    const docSize = Buffer.byteLength(doc.content, "utf-8");
    if (docSize > MAX_DOC_SIZE_BYTES) {
      throw new Error(
        `Document "${doc.name}" exceeds size limit (${Math.floor(docSize / 1024 / 1024)}MB > 50MB)`,
      );
    }
  }

  // Generate filename
  const projectName = sanitizeFilename(meta.name);
  const date = new Date().toISOString().split("T")[0];
  const filename = `${projectName}-docs-${date}.zip`;

  // Handle JSON format (simple export)
  if (format === "json") {
    const jsonData = JSON.stringify(docs, null, 2);
    const base64 = Buffer.from(jsonData, "utf-8").toString("base64");
    return {
      filename: `${projectName}-docs-${date}.json`,
      contentType: "application/json",
      data: base64,
      docCount: docs.length,
      docIds: docs.map((d) => d.id),
    };
  }

  // Build ZIP
  const zip = new JSZip();

  // Add README
  zip.file("README.md", generateReadmeContent(meta.name, docs.length));

  // Add docs.json (full backup)
  zip.file("docs.json", JSON.stringify(docs, null, 2));

  // Add markdown files
  const markdownFolder = zip.folder("markdown");
  if (!markdownFolder) {
    throw new Error("Failed to create markdown folder in ZIP");
  }

  // Resolve filename conflicts
  const filenameMap = resolveFilenameConflicts(docs);

  for (const doc of docs) {
    const mdFilename = filenameMap.get(doc.id) ?? "untitled.md";
    markdownFolder.file(mdFilename, doc.content);
  }

  // Generate ZIP buffer
  const zipBuffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  // Check ZIP size
  if (zipBuffer.byteLength > MAX_ZIP_SIZE_BYTES) {
    throw new Error(
      `Export exceeds size limit (${Math.floor(zipBuffer.byteLength / 1024 / 1024)}MB > 100MB)`,
    );
  }

  // Convert to base64
  const base64 = zipBuffer.toString("base64");

  return {
    filename,
    contentType: "application/zip",
    data: base64,
    docCount: docs.length,
    docIds: docs.map((d) => d.id),
  };
}
