/**
 * Project Resource Export
 *
 * Unified export for project docs, rules, and skills as ZIP format.
 */

import JSZip from "jszip";
import {
  loadProjectDocs,
  loadProjectMeta,
  loadProjectRules,
  loadProjectSkills,
} from "./project-store.js";
import type { ProjectDoc, ProjectRule, ProjectSkill } from "./types.js";

// ─── Types ───

export type ResourceType = "docs" | "rules" | "skills";

export interface ResourceExportOptions {
  /** Project ID */
  projectId: string;
  /** Resource types to export (required, at least one) */
  resourceTypes: ResourceType[];
  /** Document IDs to export (optional, exports all if not provided) */
  docIds?: string[];
  /** Rule IDs to export (optional) */
  ruleIds?: string[];
  /** Skill IDs to export (optional) */
  skillIds?: string[];
}

export interface ResourceExportResult {
  /** Generated filename */
  filename: string;
  /** MIME type */
  contentType: string;
  /** Base64-encoded ZIP data */
  data: string;
  /** Export statistics */
  stats: {
    docs: number;
    rules: number;
    skills: number;
    total: number;
  };
  /** Export timestamp (epoch ms) */
  exportedAt: number;
}

export interface ManifestResource {
  id: string;
  name: string;
  createdAt: number;
}

export interface Manifest {
  version: string;
  exportedAt: number;
  projectId: string;
  projectName: string;
  resources: {
    docs: ManifestResource[];
    rules: ManifestResource[];
    skills: ManifestResource[];
  };
  stats: {
    docs: number;
    rules: number;
    skills: number;
    total: number;
  };
}

// ─── Constants ───

const MAX_ZIP_SIZE_BYTES = 100 * 1024 * 1024; // 100MB
const MAX_RESOURCE_SIZE_BYTES = 50 * 1024 * 1024; // 50MB per resource
const ILLEGAL_FILENAME_CHARS = /[/:*?"<>|\\]/g;

// ─── Filename sanitization ───

/**
 * Sanitize filename for safe filesystem usage
 */
function sanitizeFilename(name: string): string {
  if (!name || name.trim() === "") {
    return "untitled";
  }
  // Replace illegal characters and spaces with dash
  let sanitized = name.replace(ILLEGAL_FILENAME_CHARS, "-").replace(/\s+/g, "-");
  // Trim and collapse multiple dashes
  sanitized = sanitized.trim().replace(/-+/g, "-");
  // Remove leading/trailing dashes
  sanitized = sanitized.replace(/^-+|-+$/g, "");
  // Fallback if empty after sanitization
  if (!sanitized) {
    return "untitled";
  }
  return sanitized;
}

// ─── Resource metadata helpers ───

/**
 * Get resource name based on type
 */
function getResourceName(
  resource: ProjectDoc | ProjectRule | ProjectSkill,
  type: ResourceType,
): string {
  if (type === "rules") {
    return (resource as ProjectRule).title;
  }
  return (resource as ProjectDoc | ProjectSkill).name;
}

/**
 * Create manifest resource entry
 */
function createManifestEntry(
  resource: ProjectDoc | ProjectRule | ProjectSkill,
  type: ResourceType,
): ManifestResource {
  return {
    id: resource.id,
    name: getResourceName(resource, type),
    createdAt: resource.createdAt,
  };
}

/**
 * Check resource size
 */
function checkResourceSize(content: string, name: string, type: ResourceType): void {
  const size = Buffer.byteLength(content, "utf-8");
  if (size > MAX_RESOURCE_SIZE_BYTES) {
    const typeLabel = type === "docs" ? "Document" : type === "rules" ? "Rule" : "Skill";
    throw new Error(
      `${typeLabel} "${name}" exceeds size limit (${Math.floor(size / 1024 / 1024)}MB > 50MB)`,
    );
  }
}

// ─── README generation ───

/**
 * Generate README content for the exported ZIP
 */
function generateReadmeContent(
  projectName: string,
  stats: { docs: number; rules: number; skills: number; total: number },
): string {
  const date = new Date().toISOString().split("T")[0];
  const parts: string[] = [];

  if (stats.docs > 0) {
    parts.push(`- docs/: ${stats.docs} document(s)`);
  }
  if (stats.rules > 0) {
    parts.push(`- rules/: ${stats.rules} rule(s)`);
  }
  if (stats.skills > 0) {
    parts.push(`- skills/: ${stats.skills} skill(s)`);
  }

  return `# ${projectName} - Resource Export

Exported from OpenClaw on ${date}

This archive contains ${stats.total} resource(s):

${parts.join("\n")}

## Structure

- manifest.json: Export manifest with resource metadata
- README.md: This file
${stats.docs > 0 ? "- docs/: Project documents (each with .md and .json files)" : ""}
${stats.rules > 0 ? "- rules/: Project rules (each with .md and .json files)" : ""}
${stats.skills > 0 ? "- skills/: Project skills (each with .md and .json files)" : ""}

## Usage

You can import these resources back into OpenClaw or use them in any Markdown-compatible tool.

Generated by OpenClaw (https://openclaw.ai)
`;
}

// ─── Export function ───

/**
 * Export project resources as ZIP
 */
export async function exportProjectResources(
  options: ResourceExportOptions,
): Promise<ResourceExportResult> {
  const { projectId, resourceTypes, docIds, ruleIds, skillIds } = options;

  // Validate resource types
  if (!resourceTypes || resourceTypes.length === 0) {
    throw new Error("At least one resource type must be specified");
  }

  // Load project metadata
  const meta = loadProjectMeta(projectId);
  if (!meta) {
    throw new Error(`Project ${projectId} not found`);
  }

  const exportedAt = Date.now();

  // Prepare resources
  const docs: ProjectDoc[] = [];
  const rules: ProjectRule[] = [];
  const skills: ProjectSkill[] = [];

  // Load and filter docs
  if (resourceTypes.includes("docs")) {
    const allDocs = loadProjectDocs(projectId);
    if (docIds && docIds.length > 0) {
      const filtered = allDocs.filter((doc) => docIds.includes(doc.id));
      docs.push(...filtered);
    } else {
      docs.push(...allDocs);
    }
  }

  // Load and filter rules
  if (resourceTypes.includes("rules")) {
    const allRules = loadProjectRules(projectId);
    if (ruleIds && ruleIds.length > 0) {
      const filtered = allRules.filter((rule) => ruleIds.includes(rule.id));
      rules.push(...filtered);
    } else {
      rules.push(...allRules);
    }
  }

  // Load and filter skills
  if (resourceTypes.includes("skills")) {
    const allSkills = loadProjectSkills(projectId);
    if (skillIds && skillIds.length > 0) {
      const filtered = allSkills.filter((skill) => skillIds.includes(skill.id));
      skills.push(...filtered);
    } else {
      skills.push(...allSkills);
    }
  }

  // Check if any resources to export
  const totalResources = docs.length + rules.length + skills.length;
  if (totalResources === 0) {
    throw new Error("No resources found to export");
  }

  // Check resource sizes
  for (const doc of docs) {
    checkResourceSize(doc.content, doc.name, "docs");
  }
  for (const rule of rules) {
    checkResourceSize(rule.content, rule.title, "rules");
  }
  for (const skill of skills) {
    checkResourceSize(skill.content, skill.name, "skills");
  }

  // Build manifest
  const manifest: Manifest = {
    version: "1.0",
    exportedAt,
    projectId,
    projectName: meta.name,
    resources: {
      docs: docs.map((d) => createManifestEntry(d, "docs")),
      rules: rules.map((r) => createManifestEntry(r, "rules")),
      skills: skills.map((s) => createManifestEntry(s, "skills")),
    },
    stats: {
      docs: docs.length,
      rules: rules.length,
      skills: skills.length,
      total: totalResources,
    },
  };

  // Build ZIP
  const zip = new JSZip();

  // Add manifest
  zip.file("manifest.json", JSON.stringify(manifest, null, 2));

  // Add README
  zip.file("README.md", generateReadmeContent(meta.name, manifest.stats));

  // Add docs
  if (docs.length > 0) {
    const docsFolder = zip.folder("docs");
    if (!docsFolder) {
      throw new Error("Failed to create docs folder in ZIP");
    }
    for (const doc of docs) {
      docsFolder.file(`${doc.id}.md`, doc.content);
      docsFolder.file(
        `${doc.id}.json`,
        JSON.stringify(
          {
            id: doc.id,
            name: doc.name,
            createdAt: doc.createdAt,
            updatedAt: doc.updatedAt,
          },
          null,
          2,
        ),
      );
    }
  }

  // Add rules
  if (rules.length > 0) {
    const rulesFolder = zip.folder("rules");
    if (!rulesFolder) {
      throw new Error("Failed to create rules folder in ZIP");
    }
    for (const rule of rules) {
      rulesFolder.file(`${rule.id}.md`, rule.content);
      rulesFolder.file(
        `${rule.id}.json`,
        JSON.stringify(
          {
            id: rule.id,
            title: rule.title,
            createdAt: rule.createdAt,
            updatedAt: rule.updatedAt,
          },
          null,
          2,
        ),
      );
    }
  }

  // Add skills
  if (skills.length > 0) {
    const skillsFolder = zip.folder("skills");
    if (!skillsFolder) {
      throw new Error("Failed to create skills folder in ZIP");
    }
    for (const skill of skills) {
      skillsFolder.file(`${skill.id}.md`, skill.content);
      skillsFolder.file(
        `${skill.id}.json`,
        JSON.stringify(
          {
            id: skill.id,
            name: skill.name,
            createdAt: skill.createdAt,
            updatedAt: skill.updatedAt,
          },
          null,
          2,
        ),
      );
    }
  }

  // Generate ZIP buffer
  const zipBuffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  // Check ZIP size
  if (zipBuffer.byteLength > MAX_ZIP_SIZE_BYTES) {
    throw new Error(
      `Export exceeds size limit (${Math.floor(zipBuffer.byteLength / 1024 / 1024)}MB > 100MB)`,
    );
  }

  // Generate filename
  const _projectName = sanitizeFilename(meta.name);
  const timestamp = new Date(exportedAt)
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\..+/, "")
    .replace("T", "-");
  const filename = `project-export-${timestamp}.zip`;

  // Convert to base64
  const base64 = zipBuffer.toString("base64");

  return {
    filename,
    contentType: "application/zip",
    data: base64,
    stats: manifest.stats,
    exportedAt,
  };
}
